### ISSUE TITLE
System Design: character_catalog should add a configfile for each character

### ISSUE THREAD

**Issue by Imccccc** [Shaunwei/RealChar#165]
the file format should be 
```yaml
charactor_name: "Steve Jobs"
system: |
     ...jobs system prompt..
user: |
     ...jobs user prompt...
text_to_speech_use : ELEVEN_LABS
voice_key: xxxxxxx
```

if it is a good design, we can build this together.
